version: "3.9"
    # networks:
    #   default:
    #     ipv4_address: 10.22.33.2
    # restart: always

services:
  hortifruttiapp:
    container_name: hortifrutti-api
    working_dir: /usr/app/hortifrutti-api
    # command: npm start
    build: 
      context: .
    ports:
      - "3333:3333"
    environment:
      - MARIADB_URL=jdbc:mysql://hortifrutti_db/mdb_hortifrutti
      - TZ=America/Brasilia
      - SERVER_PORT=3306
      # - SPRING_PROFILES_ACTIVE=dev
      # - MYSQL_URL=jdbc:mysql://hortifrutti_db/mdb_hortifrutti
    volumes:
      - .:/usr/app/hortifrutti-api
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - ./:/usr/app
      - /opt/apps/logs:/opt/apps/logs
      # - /mnt/compartilhado/mavenrepo:/root/.m2/repository
    depends_on:
      - hortifrutti_db

  phpmyadminhortifrutti:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminhortifrutti
    restart: always
    links:
      - hortifrutti_db:db
    ports:
      - "8881:80"
    environment:
      PMA_HOST: hortifrutti_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PHP_UPLOAD_MAX_FILESIZE: 100MB
    depends_on:
      - hortifrutti_db
  
  hortifrutti_db:
    image: mariadb
    container_name: hortifrutti_db
    ports:
       - 3306:3306
    environment:
      # MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      # MARIADB_ROOT_PASSWORD:
      # MARIADB_HOST: hortifrutti_db
      # MARIADB_PORT: 3306
      # MARIADB_USER: root
      # MARIADB_PASSWORD: 
      # MARIADB_DB_NAME: mdb_hortifrutti
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: true
      MYSQL_ROOT_PASSWORD:
      MYSQL_HOST: hortifrutti_db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DB_NAME: mdb_hortifrutti
    volumes:
      - mysql_data:/var/lib/mysql-files
      - mysql_config:/etc/mysql
      - mysql_files:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  
volumes:
  mysql_data:
  mysql_config:
  mysql_files:

networks:
  default:
    name: hortifruttinet
    ipam:
      driver: default
      config:
        - subnet: 10.22.44.0/24
